### PR TITLE
[4.0] Add support for search panes extension.

### LINKED ISSUE #130: Support the Searchpanes
I think it would be great if you could support the [searchpanes](https://datatables.net/extensions/searchpanes/examples/initialisation/simple.html) feature. 

For now, despite I include all the required css and js for the searchpanes, and enable the option:

```
parameters([
     'searchPane' => true
 ]);
```

It displays no search panel:

### PR DESCRIPTION
**Pull request by yajra**
Fix https://github.com/yajra/laravel-datatables/issues/2463
Fix https://github.com/yajra/laravel-datatables/issues/2471
Fix #130 

## USAGE

```php
// enable search panes
->searchPanes(true)

// enable search panes with array options
->searchPanes([
    'viewTotal' => true,
    'hideCount' => false,
])

// enable search pane with SearchPane builder class
->searchPanes(SearchPane::make()->cascadePanes(false)->hideCount())
```

### CODE REVIEW

**Comment by yajra** [comment]
**Note to self:**

It appears that custom panes are not yet fully supported for server-side but the builder added on this PR is already generating a working a scripts.

https://datatables.net/extensions/searchpanes/serverside
> It is also worth noting that custom panes will not be supported by server-side processing in SearchPanes 1.1 but this is something that we are aiming to provide in the future with SearchPanes 1.2.

Also, search panes can be hooked directly to the column builder which triggers a correct ajax request.

```php
Column::make('carrier.name')
    ->searchPanes(SearchPane::make()->modelOptions(Carrier::class, 'name', 'id'))
    ->title('Carrier'),
```

**Comment by yajra** [comment]
# Server-side implementation notes

As of writing, it seems like search panes on server-side only works via column definition. To implement, the following builder options can be used:

## Implementation 1

```php
// HTML Builder
->addColumnDef([
  'searchPanes' => ['show' => true],
  'targets' => [3],
])
```

## Implementation 2

```php
use Yajra\DataTables\Html\ColumnDefinition;

// HTML Builder
->addColumnDef(fn(ColumnDefinition $definition) => $definition->searchPanes()->targets([3]))
```

## Implementation 3

```php
use Yajra\DataTables\Html\ColumnDefinition;

// HTML Builder
->searchPanes(['hideCount' => true]) // hideCount can be removed if your search pane options supports it
->addColumnDef(fn(ColumnDefinition $definition) => $definition->searchPanes()->targets([3]))
```

**Comment by quanengineering** [comment]
Finally, thanks @yajra

**Comment by matteocostantini** [comment]
Hi @yajra ,
i'm testing searchpane with serverside.
I see values in my single simple pane. (using modelOptions Column method : ->searchPanes(SearchPane::make()->modelOptions(Carrier::class,'name','name'))  )

i'm using editor to edit name.

when i click a value in my pane i see the processing but filter not applied in resultset.

Whats appen?

this column definition

{"data":"carrier.name","name":"carrier_name","title":"Carrier Name","orderable":false,"searchable":false,"searchPanes":{"options":[{"value":"MBE","label":"MBE"},{"value":"UPS","label":"UPS"},{"value":"Corriere Espresso TNT","label":"Corriere Espresso TNT"}]},"visible":true,"editField":"id_carrier"}

**Pull request merged**
