### PR TITLE
HTML title for columns labels

### PR DESCRIPTION
**Pull request by mgralikowski**
A simple update to allow set custom HTML title instead auto-generated from "title". 

Usage:
`Column::computed('image')->title('')->htmlTitle('User image thumb');`

### CODE REVIEW

**Comment by mgralikowski** [comment]
A good use case is to use a title to column reorder plugin.

```
Button::make('colvis')
->text('Columns')
->columnText("function (dt, idx) { return $(dt.column(idx).header()).prop('title'); }")
```

**Comment by mgralikowski** [comment]
Instead `html-title` we can use `titleAttr` like datatables do. What do You think?

**Comment by yajra** [comment]
Can you please link some ref where `titleAttr` is being used? The PR looks good though.

**Comment by mgralikowski** [comment]
In buttons: https://datatables.net/reference/option/buttons.buttons.titleAttr

**Comment by yajra** [comment]
I see, I think `titleAttr` would be a good one to use for consistency with the js library. Thanks!

**Comment by yajra** [comment]
Released on v4.25.0 🚀 Thanks!

**Pull request merged**
