### PR TITLE
feat: clone the "working" `Fluent` class from laravel

### LINKED ISSUE #229: Declaration of Column::data does not compatible with Fluent::data
### Error
Declaration of Yajra\DataTables\Html\Column::data(array|string $value): static must be compatible with Illuminate\Support\Fluent::data($key = null, $default = null)

### Code snippet of problem

File vendor/yajra/laravel-datatables-html/src/Html/Column.php, function data (line 305 - 310) was the reason:

```php
public function data(array|string $value): static
{
     $this->attributes['data'] = $value;

     return $this;
}
```

### System details

Operating System: Linux Debian 12
PHP Version: 8.3
Laravel Version: laravel/framework ^11.34
Laravel-Datatables Version: yajra/laravel-datatables ^11.0

### Solution

File vendor/yajra/laravel-datatables-html/src/Html/Column.php, change function data (line 305 - 310) to:
```php
public function data($key = null, $default = null): static
{
    $this->attributes['data'] = $key;

    return $this;
}
```

### PR DESCRIPTION
**Pull request by nuernbergerA**
Fixes #229
Closes https://github.com/yajra/laravel-datatables/issues/3201

Copy Laravel's "working" `Fluent` class into this code base.

### CODE REVIEW

**Comment by yajra** [comment]
I'm still hoping for a revert to the framework. If no movement by tomorrow, I will go ahead and merge this. Thanks!

**Comment by nuernbergerA** [comment]
i dont think the will revert and in my opinion the also should not revert

**Comment by yajra** [comment]
Released on v11.7.0 🚀 Thanks!

**Comment by OzanKurt** [comment]
Great!

**Pull request merged**
