### PR TITLE
Add minifiedAjax method to minify url generated when using get request.

### PR DESCRIPTION
**Pull request by yajra**
Fixes php artisan serve and IE issues on long URL.
Related Issues:
https://github.com/yajra/laravel-datatables/issues/1225
https://github.com/yajra/laravel-datatables/issues/1205
https://github.com/yajra/laravel-datatables/pull/826
https://github.com/yajra/laravel-datatables/pull/671
etc..

### USAGE
Update html method on your service class to:
```php
    /**
     * Optional method if you want to use html builder.
     *
     * @return \Yajra\Datatables\Html\Builder
     */
    public function html()
    {
        return $this->builder()
                    ->columns($this->getColumns())
                    ->minifiedAjax('')
                    ->addAction(['width' => '80px'])
                    ->parameters($this->getBuilderParameters());
    }
```

### CODE REVIEW

**Comment by isometriq** [comment]
I've tested using `minifiedAjax` method, but columns ordering and search is not working (applied). Data is transmitted, but with model default ordering. I can see lesser GET params are sent which does not cause 404 anymore, but maybe some necessary info is being stripped?

Looks like a step in the right direction 👍 

My observations:
-I feel that sending data thru GET with PHP format is too much. If you take APIs, the format is generally very compact such as `?q=search-value&f=field1|field2|field3&o=field1,asc|field2,desc`. I don't know all the intricacies of DataTables, so I may not be aware of some limitations...
-I think also sticking to GET method is necessary, since POST is for something else

**Comment by isometriq** [comment]
Hey, just noticed that using
`->ajax(url('admin/users'))`
does not seem to cause 404 errors anymore
..maybe it's a coincidence? same table and config as before

**Comment by yajra** [comment]
@isometriq thanks for testing. I forgot to commit the changes needed on the main repo. Updates released on v7.8.1. Kindly check again.

**Comment by isometriq** [comment]
Ok, I will try soon
However, in my last test, the `->ajax()` method this did not cause 404 anymore
Are we supposed to still use it or `->minifiedAjax()` only?

**Comment by yajra** [comment]
I suggest to use `minifiedAjax` because it is indeed a weird bug where Laravel returns 404 on valid routes. I also encountered that way back and was really confused on what's happening :).

**Comment by yajra** [comment]
On Laravel 5.5 release, I think I will also default it to `minifiedAjax`. Can't do it now cause its a potential BC.

**Comment by herzcthu** [comment]
This is not a fix for very big table. Still generating very long url even after minifiedAjax applied.
POST method is an only way for some case. But current version of laravel-datatables-button not support for POST method.

**Comment by yajra** [comment]
@herzcthu Does the issue occurs only export? If yes, then maybe this PR https://github.com/yajra/laravel-datatables-buttons/pull/41 would help?

**Pull request merged**
